### PR TITLE
update maven, app name, mvn command

### PR DESCRIPTION
**Pull request by Feralfeld**
Hi
the dockerfile isan´t working
- mvn url was invalid, i solved adding the new 3.8.6
- the comand mvn package is not working for me too and i change for native:compile
- the application name was wrong "jibber" but the real generated name is "benchmark-jibber" so i changed in de COPY and ENTRYPOINT

with this changes worked fine

### CODE REVIEW

**Review by krisfoster — APPROVED** [review]
Looks good

**Comment by olyagpl** [comment]
@Feralfeld, please sign the OCA in [Oracle's Contributor Agreement Application](https://oca.opensource.oracle.com/) so we can proceed and merge your PR.

**Comment by joliverc18** [comment]
Hi all, I'm failing to understand why "benchmark" was added non-explicitly. Was this done by the docker process and is "benchmark" added because of the project-name specifics? 

I didn't spot any changes that appended "benchmark" to the resulting image name

**Comment by olyagpl** [comment]
@Feralfeld, Spring Native Demo has been upgraded to use Native Image Build Tools and these inconsistencies were considered too in https://github.com/graalvm/graalvm-demos/pull/168.

**Pull request closed without merging**
