### PR TITLE
Fix docs for Java Kotlin AOT demo

### LINKED ISSUE #27: After the GraalVM 19.0.0 release, readme for java-kotlin-aot is out of date
The readme is out of date and now with version 19.0.0, you need to use `gu update native-image` before running the example

### PR DESCRIPTION
**Pull request by neomatrix369**
Added docs to README to clarify prerequisites and how to install them to enable running the Java-Kotlin-AOT example

Fixes #27

### CODE REVIEW

**Comment by fdelbrayelle** [comment]
I failed to install "native-install" in v19.2.0. I got the following message :

```
$GRAALVM_HOME/bin/gu install native-image
Skipping ULN EE channels, no username provided.
Downloading: Component catalog from www.graalvm.org
Downloading: Component catalog from www.graalvm.org
Error: Unknown component: native-image
```

Any idea?

**Comment by neomatrix369** [comment]
> I failed to install "native-install" in v19.2.0. I got the following message :
> 
> ```
> $GRAALVM_HOME/bin/gu install native-image
> Skipping ULN EE channels, no username provided.
> Downloading: Component catalog from www.graalvm.org
> Downloading: Component catalog from www.graalvm.org
> Error: Unknown component: native-image
> ```
> 
> Any idea?

Not sure, I don't get the error:

```
Downloading: Component catalog from www.graalvm.org
Processing component archive: Native Image
Component Native Image (org.graalvm.native-image) is already installed.
```

Do you want to try this in some other environment other than the place where you are doing this? Maybe on the cloud or someone else's machine. And see if the result differs.

**Comment by fdelbrayelle** [comment]
I have no other from access from now but finally I've solved the issue doing this :

` $GRAALVM_HOME/bin/gu install --file native-image-installable-svm-svmee-linux-amd64-19.2.0.jar`

After downloading the Early Adopter JAR here https://www.oracle.com/technetwork/graalvm/downloads/index.html

**Comment by neomatrix369** [comment]
@fdelbrayelle can you please raise this on the oracle/graal repo as an issue, so it gets noted. There could be an issue which you may help solve by doing this. Do let them know how you solved it. Thanks.

**Comment by neomatrix369** [comment]
Any chance of this being reviewed?

**Comment by fdelbrayelle** [comment]
I've written an issue in the repo you've sent.
But it seems it's a part of the 19.2.0 so no issue obviously :) : https://www.graalvm.org/docs/release-notes/19_2/

**Comment by olyagpl** [comment]
Installing Native Image is now a part of install steps, https://github.com/graalvm/graalvm-demos/tree/master/java-kotlin-aot#readme. I'm closing this PR. @neomatrix369 , thanks for your contribution!

**Pull request closed without merging**
