### PR TITLE
Adding Dockerfile and bash scripts to build and run Docker containers

### PR DESCRIPTION
**Pull request by neomatrix369**
@olyagpl continuing from PR #31, as per our last conversation: https://github.com/graalvm/graalvm-demos/pull/31#issuecomment-929321242

Handy Docker scripts to facilitate running the `graalvm` demos in a clean and isolated environment. The below defaults to GraalVm 21.2.0 Java 11

Build a docker image with GraalVM runtime in it:
```
   $   cd docker-images
   $   ./buildDockerImage.sh
```

Run a docker container with GraalVM runtime in it (from the root directory of the project):
```
   $   ./runDockerImage.sh
```

Run a docker container with GraalVM runtime in it (from the root directory of the project) for GUI-based apps:
```
   $   DEMO_TYPE="gui" ./runDockerImage.sh
```

To build and run examples using another version of GraalVM runtime (i.e. GraalVM 21.2.0 for Java 11), the usage is as follows:

Build a docker image with GraalVM runtime in it:
```
   $   cd docker-images
   $   ./buildDockerImage.sh "java11-21.2.0"
```

Run a docker container with GraalVM runtime in it (from the root directory of the project):
```
   $   ./runDockerImage.sh "java11-21.2.0"
```

Run a docker container with GraalVM runtime in it (from the root directory of the project) for GUI-based apps:
```
   $   DEMO_TYPE="gui" ./runDockerImage.sh "java11-21.2.0"

   (Download and run a VNCViewer and then log onto http://127.0.0.1:5900 
    via the VNCViewer to access the GUI interface. You will get an `xterm` screen,
    where you can type in your commands just like the docker console or any other CLI prompt.)
```

Note: See https://github.com/graalvm/container/pkgs/container/graalvm-ce, for a list of complete tag names to be used at CLI parameters to the above shell-scripts. A number of free or commercial [VNC Viewers](https://duckduckgo.com/?q=vnc+viewer+download&ia=web) can be found online and are fairly easy to use.

Thanks to @findepi for providing the GraalVM community with the complete set of lightweight GraalVM docker images. We have now migrated the scripts to use GraalVM's own home built docker images, your images have been helpful so far to test out many of the demos, thank you for that, please take this migration as a positive gesture.

In addition to the version of GraalVM binaries, the `graalvm-demo` container contains the following at runtime:
- GraalVM components: espresso, python, nodejs, native-image, llvm, and the other default components that come with the GraalVM binary 
- Java 8 (OpenJDK version)
- Maven 3.8.1
- Gradle 7.2
- Micronaut Starter binary
- wrk (workload generator) binary 
- jmeter
- Scala and sbt
- dependencies in place to be able to run GUI based apps from inside a docker container

### CODE REVIEW

**Comment by neomatrix369** [comment]
Testing build docker container against the below examples:

- [x] espresso-jshell
- [ ] fastR-examples @ 4234443
- [ ] functionGraphDemo
- [ ] galaaz-ggplot
- [ ] graalpython-notebook-example
- [ ] hello-graal
- [ ] java-kotlin-aot
- [ ] java-simple-stream-benchmark
- [ ] js-java-async-helidon
- [ ] micronaut-nativeimage
- [ ] micronaut-webapp
- [ ] mle-oracle
- [ ] mn-python
- [ ] multithreading-demo
- [ ] native-image-configure-examples
- [ ] native-image-workshop
- [ ] native-list-dir
- [ ] native-netty-plot
- [ ] polyglot-debug
- [ ] polyglot-javascript-java-r
- [ ] scala-examples
- [ ] spring-r

In case, the test fails or cannot be tested, could be due to one or both of these reasons:
- example is a GUI based example
- example may already come with its own docker or another container-based solution

**Comment by olyagpl** [comment]
@neomatrix369 , thanks! I'll review asap.

**Comment by neomatrix369** [comment]
> @neomatrix369 , thanks! I'll review asap.

Thanks, try to run this on your own machine and see how it works, I will continue to test other examples using the docker container, please don't merge it yet (even if you are happy with the current PR).

**Comment by neomatrix369** [comment]
@olyagpl we can now build and run any version of GraalVM (community version) using the current script - I'm now testing the rest of the demo apps to see if they work well, otherwise I will raise separate issues for the respective apps

**Comment by neomatrix369** [comment]
`micronaut-python` works with the fix via fad1795:

```
root@4f2411b70011:/graalvm-demos/micronaut-python# gradle run
Starting a Gradle Daemon, 1 busy and 2 incompatible and 4 stopped Daemons could not be reused, use --status for details

> Task :compileJava
Note: Creating bean classes for 2 type elements

> Task :run
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.0.3)

02:31:46.350 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 45864ms. Server Running: http://4f2411b70011:8080
<=========----> 75% EXECUTING [5m 23s]
> :run
```
^^^ running inside the dockr container

**Comment by neomatrix369** [comment]
> Great work, Mani!
> 
> 1. We should be using GraalVM Community container images from GitHub Container Registry, https://github.com/graalvm/container/pkgs/container/graalvm-ce.
> 2. We should notify the users that  "these demos were tested and are known to work with GraalVM 21.2.0 builds based on JDK 11" ( I've already specified that in the main README).
> 3. Could you please rephrase  this sentence, Running section in
>    https://github.com/neomatrix369/graalvm-demos/blob/provide-Docker-scripts/README.md: [
>    Screenshot 2021-10-11 at 13 52 17
> 4. The script `./buildDockerImage.sh "21.2.0-java11-all` didn't run for me. So again, it will make sense to use GraalVM CE images:
>    Screenshot 2021-10-11 at 13 53 37
> 
> Olya

You need to build the local image with this command first and then run it, using the "./runDockerImage.sh "21.2.0-java11-all" docker can't find it in the local repo (this image exists on the remote repo), here are the steps you should do first:

```
### One-off
cd docker-image
./buildDockerImage.sh "21.2.0-java11-all"
cd ...
```

```
### Everytime thereafter
./runDockerImage.sh "21.2.0-java11-all"
```

**Comment by neomatrix369** [comment]
@findepi while building images I came across an issue to do with `/etc/../sources.list` when using `-java8` related images from `findepi/graalvm`, should I raise this on your github?

**Comment by neomatrix369** [comment]
@timfel Running `mvn compile` for the `graalpython-notebook-example` demo gives us this issue https://github.com/graalvm/graalvm-demos/pull/93#issuecomment-939198205, you can also reproduce it via the docker container mentioned on the PR.

**Comment by neomatrix369** [comment]
Thanks for your feedback @eregon I really appreciate it 

Especially you are nitpicking and finding cruft, which I would also like to remove from the scripts and config files -- a second pair of eyes surely helps.

**Review by olyagpl — APPROVED** [review]

**Comment by olyagpl** [comment]
We will gradually improve and make things less and less manual as we go along. I'm merging this PR.
Thanks Mani and everyone involved!

**Comment by neomatrix369** [comment]
Thanks @olpaw for the https://github.com/graalvm/graalvm-demos/tree/master/native-hello-module demo example, I have tested it in our Docker container for GraalVM 21.3.0, and it works fine.

You can also try it or other demos by doing this:

```bash
$ git clone https://github.com/graalvm/graalvm-demos/
$ ./runDockerImage.sh "java11-21.3.0"

### At the prompt inside the container do:
root@.....:/graalvm-demos# cd native-hello-module

### perform all the steps for the demo
root@.....:/graalvm-demos#
```

**Comment by neomatrix369** [comment]
> I'm checking with @ezzarghili, I think there is a way to install rpm's for each component/language, and that should automatically install all required system dependencies. They are currently working on having 21.3 Docker images with those rpm packages.
Maybe we can even have a Docker image with all components pre-installed, that sounds ideal for this use-case, isn't it?

@eregon As I'm getting ready to continue from this point on again, I wanted to check if the above thing you mentioned sometime back is available with the latest GraalVM  21.3 docker images? I have just built a 21.3 docker image for GraalVM demos. If not, it's fine, I can build on top of the GraalVM docker image (as you were suggesting earlier) and maybe it needs fewer dependencies - which could be to our advantage.

**Comment by neomatrix369** [comment]
Hey @ezzarghili would you be able to help me out with this query https://github.com/graalvm/graalvm-demos/pull/93#issuecomment-966554348 as you manage all things docker for the GraalVM team

**Comment by eregon** [comment]
Yes, @ezzarghili should be the best contact about this and in general if you have any issue related to these Docker images, https://github.com/graalvm/container is the place to report them.
That repository still needs a README, cc @abdelhaira

**Comment by ezzarghili** [comment]
Public yum rpms already exist on https://yum.oracle.com/repo/OracleLinux/OL7/graalvm/community/x86_64/index.html and https://yum.oracle.com/repo/OracleLinux/OL8/graalvm/community/x86_64/index.html
If you use one of the compact (rpm based images) available you should be able to use microdnf (ol8) or yum (ol7) to install the packages you, the repos should be already configured for you.

https://github.com/graalvm/container/pkgs/container/jdk is the minimal image to build on, but there is also the native-image and nodejs ones.

Please keep in mind that for experimental languages (graalpython, truffleruby...) the rpms are only available for Year.N.0 releases (i.e 21.3.0 but not 21.3.1+).

**Comment by eregon** [comment]
I've tried the above and to give an idea how it works:
```
$ docker run --rm -it ghcr.io/graalvm/jdk:java17-21.3.0 bash
bash-4.4# microdnf install graalvm21-ce-11-ruby-devel-21.3.0
Downloading metadata...
Downloading metadata...
Downloading metadata...
Package                                                                                           Repository                            Size
Installing:                                                                                                                                 
 graalvm21-ce-11-jdk-21.3.0-1.el8.x86_64                                                          ol8_graalvm_community             205.7 MB
 graalvm21-ce-11-llvm-21.3.0-1.el8.x86_64                                                         ol8_graalvm_community              41.9 MB
 graalvm21-ce-11-llvm-toolchain-21.3.0-1.el8.x86_64                                               ol8_graalvm_community              32.7 MB
 graalvm21-ce-11-ruby-21.3.0-1.el8.x86_64                                                         ol8_graalvm_community              55.1 MB
 graalvm21-ce-11-ruby-devel-21.3.0-1.el8.x86_64                                                   ol8_graalvm_community               4.7 kB
 keyutils-libs-devel-1.5.10-6.el8.x86_64                                                          ol8_baseos_latest                  48.8 kB
 krb5-devel-1.18.2-8.3.el8_4.x86_64                                                               ol8_baseos_latest                 572.8 kB
 libcom_err-devel-1.45.6-1.el8.x86_64                                                             ol8_baseos_latest                  39.1 kB
 libkadm5-1.18.2-8.3.el8_4.x86_64                                                                 ol8_baseos_latest                 190.8 kB
 libpkgconf-1.4.2-1.el8.x86_64                                                                    ol8_baseos_latest                  35.6 kB
 libselinux-devel-2.9-5.el8.x86_64                                                                ol8_baseos_latest                 204.6 kB
 libsepol-devel-2.9-2.el8.x86_64                                                                  ol8_baseos_latest                  87.7 kB
 libverto-devel-0.3.0-5.el8.x86_64                                                                ol8_baseos_latest                  18.2 kB
 openssl-devel-1:1.1.1g-15.el8_3.x86_64                                                           ol8_baseos_latest                   2.4 MB
 pcre2-devel-10.32-2.el8.x86_64                                                                   ol8_baseos_latest                 619.3 kB
 pcre2-utf16-10.32-2.el8.x86_64                                                                   ol8_baseos_latest                 234.2 kB
 pcre2-utf32-10.32-2.el8.x86_64                                                                   ol8_baseos_latest                 225.6 kB
 pkgconf-1.4.2-1.el8.x86_64                                                                       ol8_baseos_latest                  38.9 kB
 pkgconf-m4-1.4.2-1.el8.noarch                                                                    ol8_baseos_latest                  17.4 kB
 pkgconf-pkg-config-1.4.2-1.el8.x86_64                                                            ol8_baseos_latest                  15.5 kB
 zlib-devel-1.2.11-17.el8.x86_64                                                                  ol8_baseos_latest                  58.9 kB
...
(so system dependencies are installed automatically)
bash-4.4# export PATH=/usr/lib64/graalvm/graalvm21-ce-java17/bin:$PATH
bash-4.4# ruby -v
truffleruby 21.3.0, like ruby 2.7.4, GraalVM CE Native [x86_64-linux]
```

You need to be careful to match the graalvm and java versions, otherwise you'll end up installing another graalvm in that image, i.e., installing another `graalvm*11-jdk-*` package.

**Comment by eregon** [comment]
Currently it's necessary to manually run the post-install hook for ruby, but it shouldn't (filed internally as GR-35132).
So
```
bash-4.4# /usr/lib64/graalvm/graalvm21-ce-java17/languages/ruby/lib/truffle/post_install_hook.sh
```
after that `microdnf install`

**Pull request merged**
