### PR TITLE
Upgrading Spring Boot example to Spring Boot 3 RC1

### PR DESCRIPTION
**Pull request by jabrena**

### CODE REVIEW

**Comment by jabrena** [comment]
Pending to receive the Ok from the process:

- https://oca.opensource.oracle.com/

**Comment by jabrena** [comment]
OCA Verified

**Review by olyagpl — APPROVED** [review]

**Comment by jabrena** [comment]
Nice @fniephaus commit. Less code

**Comment by fniephaus** [comment]
Thanks, @jabrena. I just used https://start.spring.io/ to generate the `pom.xml` and added the dependencies back in.

**Review by fniephaus — APPROVED** [review]
LGTM. Thanks a lot!

**Comment by jabrena** [comment]
Thanks you @fniephaus, @shaunsmith & @olyagpl.

I am learning in the journey.

Next week, I will send another PR with some new improvement in this particular example and a minor upgrade in the `musl` script. In the other hand, I have doubts if `graal` dev team reported the issue with latest `musl` version.

- https://github.com/oracle/graal/issues/4076

Current examples are using 10.2.1 version but it is not the latest one. If you upgrade to the latest version, the examples crashes.

Have a good weekend, next week a new PR.

Cheers

Juan Antonio

**Pull request merged**
