### PR TITLE
Import polyglot chat app with Micronaut, Python, and R

### PR DESCRIPTION
**Pull request by timfel**
@steve-s could you check if this looks fine?

### CODE REVIEW

**Comment by timfel** [comment]
@alina-yur this is the code for the magazine article

**Review by alina-yur — APPROVED** [review]
Looks good to me. @olyagpl can you please review?

**Review by olyagpl — CHANGES_REQUESTED** [review]
For consistency with other demos, we need to shortly tell how to run the demo.
Can somebody please extend this README with steps?

**Comment by steve-s** [comment]
@timfel yes looks good. Thanks. I guess you want to include all the Python packages to make it simpler to get started?

**Comment by timfel** [comment]
@olyagpl I updated the README, is that sufficient?

@steve-s yes, I wanted to include the Python packages, it's pure Python and makes it simpler than explaining how to set up a venv.

**Pull request merged**
